#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
err()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — measure the tester's own access network. No cloud resources.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# This wizard answers exactly one question: is the ~4 Mbit/s upload seen against
# the Singapore exit node a ceiling of the China Telecom 5G access network, or a
# property of the international route? It creates nothing and spends nothing.

# Everything captured is a live public address or a location, so it stays out of
# the repository. Private, mode 600, same convention as do-route-wizard.sh.
ENV_FILE="/private/tmp/vpn-gcore-access-baseline.env"
RUN_DIR="/private/tmp/vpn-gcore-access-$(date +%Y%m%d-%H%M%S)"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Reference figure to compare against: the aggregate iperf3 upload measured to
# the sgp1 exit node on 2026-09-02 off-peak, run folder
# /private/tmp/vpn-gcore-do-stage2-20260902-045041. Update if that changes.
REF_UPLOAD_MBIT=3.96
REF_LABEL="sgp1 exit node, 2026-09-02 off-peak"

umask 077
mkdir -p "$RUN_DIR"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

# shellcheck source=scripts/proof-lifecycle.sh
. "$REPO_ROOT/scripts/proof-lifecycle.sh"

jqp() { local prog="$1"; shift; python3 -c "import json,sys
$prog" "$@"; }

capture() {
  proof_capture "$RUN_DIR" "$@"
}

banner "Access network baseline — how fast is this connection, really?"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — local only"
say "This wizard measures the access network the tester is sitting on."
say "It creates no cloud resource, spends nothing, and needs no API token."
printf '\n'
say "Output folder: $RUN_DIR"
printf '\n'

MISSING=0
for tool in curl python3 ping dig; do
  if command -v "$tool" >/dev/null 2>&1; then
    step "found $tool"
  else
    warn "missing required tool: $tool"; MISSING=1
  fi
done
if command -v speedtest-cli >/dev/null 2>&1; then
  step "found speedtest-cli"
else
  warn "speedtest-cli is missing — it is the core of this wizard."
  note "  brew install speedtest-cli"
  MISSING=1
fi
[[ "$MISSING" -eq 0 ]] || { printf '\n'; warn "install the missing tools and re-run"; exit 1; }
printf '\n'
pause "Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
# Identical check to do-route-wizard.sh Stage 5, deliberately: a baseline taken
# through the commercial VPN measures Gcore Tokyo, not China Telecom, and would
# be worse than no baseline because it looks plausible.
stage "Turn the commercial VPN OFF"
warn "A baseline measured through the commercial VPN is not a baseline. It"
warn "measures the VPN. Every number here must come from the bare path."
printf '\n'
step "Quit Shadowrocket / any other VPN client completely."
step "Confirm the laptop is tethered to the China Telecom 5G handset in Hangzhou."
step "Pause downloads, cloud backups and OS updates. Keep the handset still."
printf '\n'
pause "Press Enter when the VPN is fully off."

while true; do
  printf '\n'
  say "Checking the live path…"
  FAKE_DNS=$(dig +short +time=3 +tries=1 example.com 2>/dev/null | grep -c '^198\.18\.' || true)
  ORG=$(curl -4 -sS --max-time 10 https://ipinfo.io/org 2>/dev/null || echo unknown)
  CITY=$(curl -4 -sS --max-time 10 https://ipinfo.io/city 2>/dev/null || echo unknown)
  CC=$(curl -4 -sS --max-time 10 https://ipinfo.io/country 2>/dev/null || echo unknown)
  if [[ -z "$CC" || "$CC" == unknown ]]; then
    CC=$(curl -4 -sS --max-time 10 https://api.country.is 2>/dev/null \
         | jqp 'print(json.load(sys.stdin).get("country","unknown"))' 2>/dev/null || echo unknown)
    [[ "$CC" == unknown ]] || note "ipinfo.io unreachable; fell back to api.country.is"
  fi
  say "resolver  : $( [[ "$FAKE_DNS" -gt 0 ]] && echo 'FAKE-IP 198.18/15 — a tunnel is still capturing DNS' || echo 'clean' )"
  say "public org: $ORG"
  say "location  : $CITY / $CC"
  printf '\n'

  if [[ "$FAKE_DNS" -gt 0 ]]; then
    warn "A VPN or proxy is still intercepting DNS. Turn it fully off."
  elif printf '%s' "$ORG$CC" | grep -Eqi 'gcore|g-core|akamai|linode|vultr|digitalocean|datacamp|m247|JP$'; then
    warn "The visible exit looks like a datacenter or a Japan exit, not China Telecom."
  elif [[ "$CC" == "CN" ]]; then
    say "Path looks like the bare China Telecom access network."
    { echo "vpn_state=off"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=verified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    break
  else
    warn "Country reads '$CC', expected CN."
    note "Both geolocation services being unreachable is itself plausible on bare"
    note "China Telecom and is not by itself evidence that a VPN is still up."
  fi

  printf '\n'
  if [[ "$FAKE_DNS" -eq 0 ]] \
     && confirm "Override: VPN is off and this is China Telecom 5G in Hangzhou. Proceed?"; then
    { echo "vpn_state=off-operator-confirmed"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=unverified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    warn "Recorded as operator-confirmed with unverified geolocation."
    break
  fi
  confirm "Re-check?" || { warn "Refusing to measure through a tunnel."; exit 1; }
done
ask SESSION_KIND "Session kind — off-peak or peak [off-peak]:"
SESSION_KIND="${SESSION_KIND:-off-peak}"
echo "session_kind=$SESSION_KIND" >> "$RUN_DIR/path-state.txt"
write_env SESSION_KIND "$SESSION_KIND"
pause "Press Enter."

# ── Stage 3 ───────────────────────────────────────────────────────────────
# The 2026-09-02 exit-node run left every one of these fields as "unknown" in
# result.md. They cost nothing to capture and the benchmark protocol asks for
# them, so capture them while the tester is sitting in front of the handset.
stage "Record the radio and tethering conditions"
say "The benchmark protocol asks for these. Last run recorded them as unknown."
say "Answer from the handset's own status screen; press Enter to skip any one."
printf '\n'
ask HANDSET       "Handset make and model:"
ask RADIO_STATE   "Radio the handset reports — 5G or LTE [5G]:"; RADIO_STATE="${RADIO_STATE:-5G}"
ask SIGNAL        "Signal strength, dBm or bars, if shown:"
ask TETHER_METHOD "Tethering method — USB, Wi-Fi hotspot, Bluetooth [Wi-Fi hotspot]:"
TETHER_METHOD="${TETHER_METHOD:-Wi-Fi hotspot}"
ask CARRIER_PLAN  "Carrier plan, if it has a known speed cap:"
ask LOCAL_NOTES   "Anything else about local conditions:"
{ echo "handset=$HANDSET"; echo "radio_state=$RADIO_STATE"; echo "signal=$SIGNAL"
  echo "tether_method=$TETHER_METHOD"; echo "carrier_plan=$CARRIER_PLAN"
  echo "local_notes=$LOCAL_NOTES"
  echo "gateway=$(route -n get default 2>/dev/null | awk '/gateway/{print $2}' || echo unknown)"
} > "$RUN_DIR/conditions.txt"
for k in HANDSET RADIO_STATE SIGNAL TETHER_METHOD; do write_env "$k" "${!k}"; done
printf '\n'
say "Written to $RUN_DIR/conditions.txt"
pause "Press Enter to start measuring."

# ── Stage 4 ───────────────────────────────────────────────────────────────
# The load-bearing stage. A nearby domestic server keeps the international
# egress out of the measurement, so whatever ceiling shows up here is the radio,
# the tether and the local carrier — not the route to Singapore.
stage "Access-network capability floor"
say "Three runs against the nearest server Ookla will offer us."
say "That server may NOT be inside China — Ookla's list is unreliable from"
say "this network and has returned North American servers only. That is fine:"
say "whatever upload this achieves is a proven LOWER BOUND on what the access"
say "network can do, which is exactly what the verdict needs."
printf '\n'
warn "Keep the handset still and stop using the network for about 3 minutes."
printf '\n'
pause "Press Enter to begin."
printf '\n'

for i in 1 2 3; do
  say "capability run $i of 3…"
  capture "domestic-speedtest-$i" speedtest-cli --secure --json
done
printf '\n'
say "Done. Parsed in the final stage."
pause "Press Enter."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "International reference and latency control"
say "Now the same test against the nearest server OUTSIDE mainland China."
say "The gap between this and Stage 4 is the international egress penalty."
printf '\n'
say "Finding nearby non-China servers…"
printf '\n'
speedtest-cli --list 2>/dev/null > "$RUN_DIR/server-list.txt" || true
INTL_SERVER=""
INTL_DEFAULT=""
if [[ -s "$RUN_DIR/server-list.txt" ]]; then
  python3 - "$RUN_DIR/server-list.txt" > "$RUN_DIR/server-candidates.txt" <<'PY'
import re, sys
rows = []
for line in open(sys.argv[1], encoding="utf-8", errors="replace"):
    m = re.match(r'\s*(\d+)\)\s+(.*?)\s+\(([^)]*)\)\s+\[([\d.]+) km\]', line)
    if not m:
        continue
    sid, sponsor, place, km = m.groups()
    country = place.split(",")[-1].strip()
    if country.lower() in ("china", "cn"):
        continue
    rows.append((float(km), sid, sponsor.strip(), place.strip()))
rows.sort()
for km, sid, sponsor, place in rows[:8]:
    print("%s\t%s\t%s\t%.0f km" % (sid, sponsor, place, km))
PY
  if [[ -s "$RUN_DIR/server-candidates.txt" ]]; then
    while IFS=$'\t' read -r sid sponsor place km; do
      step "$sid  $place  — $sponsor  ($km)"
    done < "$RUN_DIR/server-candidates.txt"
    INTL_DEFAULT=$(head -1 "$RUN_DIR/server-candidates.txt" | cut -f1)
  fi
fi
printf '\n'
if [[ -n "$INTL_DEFAULT" ]]; then
  ask INTL_SERVER "Server id to use [$INTL_DEFAULT]:"; INTL_SERVER="${INTL_SERVER:-$INTL_DEFAULT}"
else
  warn "Could not read the server list — the international leg will be skipped."
  note "Not fatal: Stage 4 alone answers the ceiling question."
  INTL_SERVER=""
fi

if [[ -n "$INTL_SERVER" ]]; then
  printf '\n'
  say "international run against server ${INTL_SERVER}…"
  write_env INTL_SERVER "$INTL_SERVER"
  capture "international-speedtest" speedtest-cli --secure --json --server "$INTL_SERVER"
fi

printf '\n'
# Same control target and count as do-route-wizard.sh, so sessions compare.
say "Latency control: 100 pings to 1.1.1.1, matching the exit-node runs."
capture "control-ping-cloudflare" ping -c 100 -i 0.3 1.1.1.1
printf '\n'
pause "Press Enter for the verdict."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Verdict — ceiling or route?"
python3 - "$RUN_DIR" "$REF_UPLOAD_MBIT" "$REF_LABEL" > "$RUN_DIR/summary.md" <<'PY'
import glob, json, os, re, statistics as st, sys

run_dir, ref_up, ref_label = sys.argv[1], float(sys.argv[2]), sys.argv[3]

# A server is only "near enough" to prove a LOCAL ceiling. A low upload to a
# distant server is ambiguous: it could be the radio, or it could be that route.
NEAR_KM = 1000

def load(path):
    """speedtest-cli --json output, wrapped by capture()'s echoed command line."""
    try:
        raw = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return None
    m = re.search(r'\{.*\}', raw, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None

def mbit(v):
    return v / 1e6

def where(d):
    s = d.get("server", {})
    return (s.get("name", "?"), s.get("country", "?"), float(s.get("d", 0) or 0))

runs = [d for d in (load(p) for p in sorted(
    glob.glob(os.path.join(run_dir, "domestic-speedtest-*.txt")))) if d]
intl = load(os.path.join(run_dir, "international-speedtest.txt"))

out = []
w = out.append
w("# Access network baseline\n")
for line in open(os.path.join(run_dir, "path-state.txt"), encoding="utf-8"):
    w("    " + line.rstrip())
w("")
w("Raw captures: %s\n" % run_dir)

if not runs:
    w("## Result: INCONCLUSIVE\n")
    w("No speedtest produced parseable JSON. Check the raw files in the run")
    w("folder; speedtest-cli may have failed to reach a server at all.")
    print("\n".join(out))
    raise SystemExit(0)

w("## Capability runs\n")
w("| run | server | distance | down Mbit/s | up Mbit/s | ping ms |")
w("|---|---|---|---|---|---|")
for i, d in enumerate(runs, 1):
    name, country, km = where(d)
    w("| %d | %s, %s | %.0f km | %.1f | %.1f | %.1f |" % (
        i, name, country, km, mbit(d["download"]), mbit(d["upload"]), d.get("ping", 0)))
w("")

ups = [mbit(d["upload"]) for d in runs]
dns = [mbit(d["download"]) for d in runs]
best_up, med_up, med_dn = max(ups), st.median(ups), st.median(dns)
nearest_km = min(where(d)[2] for d in runs)
any_cn = any(where(d)[1].lower() in ("china", "cn") for d in runs)
near_enough = any_cn or nearest_km <= NEAR_KM

w("Best upload observed:   **%.1f Mbit/s**  (this is a proven lower bound)" % best_up)
w("Median upload:          %.1f Mbit/s" % med_up)
w("Median download:        %.1f Mbit/s" % med_dn)
w("Nearest server used:    %.0f km" % nearest_km)
w("")

if not near_enough:
    w("> Note: the nearest server Ookla offered was %.0f km away and outside" % nearest_km)
    w("> China, so this is NOT a measurement of the local ceiling. It is only a")
    w("> lower bound on what the access network can achieve.")
    w("")

if intl:
    name, country, km = where(intl)
    w("## Second reference\n")
    w("Server: %s, %s (%.0f km) — %s" % (name, country, km, intl.get("server", {}).get("sponsor", "?")))
    w("")
    w("Download %.1f Mbit/s, upload %.1f Mbit/s, ping %.1f ms" % (
        mbit(intl["download"]), mbit(intl["upload"]), intl.get("ping", 0)))
    w("")

w("## Verdict\n")
w("Reference: %.2f Mbit/s upload measured against the %s.\n" % (ref_up, ref_label))

if best_up >= ref_up * 3:
    # Valid regardless of how far the server was: a lower bound this far above
    # the exit-node figure can only mean the access network has headroom.
    w("**The route is the ceiling, not the access network.**\n")
    w("The access network reached %.1f Mbit/s upload, %.1fx what the exit node"
      % (best_up, best_up / ref_up))
    w("delivered (%.2f Mbit/s) — and it did so over %.0f km, further than"
      % (ref_up, nearest_km))
    w("Singapore. The uplink has headroom the tested route is throwing away.")
    w("")
    w("Next: one create-measure-destroy cycle against a different region, same")
    w("plan and same session kind, compared against this baseline. Note that")
    w("this does not tell you WHICH alternative region is better, only that the")
    w("access network is not what is limiting upload.")
elif best_up <= ref_up * 1.5 and near_enough:
    w("**The access network is the ceiling.**\n")
    w("A genuinely nearby server (%.0f km) reached only %.1f Mbit/s upload,"
      % (nearest_km, best_up))
    w("close to what the exit node delivered (%.2f Mbit/s). The limit is the" % ref_up)
    w("radio, the tether or the carrier. No exit node anywhere can beat it, so")
    w("no further candidates should be rented to chase upload.")
elif best_up <= ref_up * 1.5:
    w("**INCONCLUSIVE — the test could not reach a nearby server.**\n")
    w("Upload topped out at %.1f Mbit/s, but the closest server available was"
      % best_up)
    w("%.0f km away. A low number over a long path does not distinguish a" % nearest_km)
    w("local ceiling from a bad route, so this run cannot answer the question.")
    w("")
    w("Next: get a genuinely domestic server before drawing any conclusion —")
    w("Ookla's legacy list is unreliable from this network.")
else:
    w("**Mixed — neither explanation is clean.**\n")
    w("Best upload (%.1f Mbit/s) sits between the exit-node figure (%.2f) and"
      % (best_up, ref_up))
    w("a clear headroom result. Re-run in the 20:00-23:00 peak window before")
    w("renting anything, since congestion is the likeliest difference.")
w("")
w("## Caveat\n")
w("This says nothing about Tokyo. It measures the access network only, and")
w("DigitalOcean has no Japan region. See docs/adr/0002.")
w("")
w("Speedtest uses multiple parallel streams and heavily peered servers, while")
w("the exit-node figure came from 2-stream iperf3. The comparison is indicative,")
w("not like-for-like; treat a gap under about 2x as noise.")

print("\n".join(out))
PY

cat "$RUN_DIR/summary.md"
printf '\n'
say "Summary written to $RUN_DIR/summary.md"
note "Nothing was created and nothing is billing — this wizard is local only."
note "Turn the commercial VPN back on when you are finished."

finish
