#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one create → test → destroy cycle against one DigitalOcean region.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Everything this wizard captures is either a live public address or an account
# identifier, so it never touches the repository. Private, mode 600, outside.
ENV_FILE="/private/tmp/vpn-gcore-do-run.env"
TOKEN_FILE="/private/tmp/vpn-gcore-do-session.env"
GUARD="/private/tmp/vpn-gcore-do-guard.sh"
SSH_KEY="/private/tmp/vpn-gcore-do-experiment-key"
RUN_DIR="/private/tmp/vpn-gcore-do-stage2-$(date +%Y%m%d-%H%M%S)"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API="https://api.digitalocean.com/v2"
TAG="vpn-gcore-experiment"

umask 077
mkdir -p "$RUN_DIR"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

api() { # api METHOD PATH [JSON-BODY]
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -sS -m 60 -X "$method" \
      -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
      -H "Content-Type: application/json" -d "$body" "$API$path"
  else
    curl -sS -m 60 -X "$method" \
      -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" "$API$path"
  fi
}

jqp() { local prog="$1"; shift; python3 -c "import json,sys
$prog" "$@"; }  # tiny json helper, no jq

capture() { # capture NAME COMMAND... — tee raw output into the run folder
  local name="$1"; shift
  printf '\n===== %s =====\n' "$name" >>"$RUN_DIR/session.log"
  { printf '$'; printf ' %q' "$@"; printf '\n'; "$@" || true; printf '\nexit_code=%s\n' "$?"; } \
    2>&1 | tee "$RUN_DIR/${name//[^A-Za-z0-9_.-]/_}.txt" >>"$RUN_DIR/session.log" || true
}

banner "DigitalOcean exit-node route test — create, measure, destroy"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — protected baseline must be intact"
say "This account holds Droplets belonging to unrelated projects. Before any"
say "write call we re-verify the baseline and fail closed if it moved."
printf '\n'

for tool in curl python3 ssh ssh-keygen ping traceroute dig; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing required tool: $tool"; exit 1; }
done
command -v iperf3 >/dev/null 2>&1 || note "iperf3 not installed locally — bidirectional test will be skipped"

[[ -r "$TOKEN_FILE" ]] || { warn "no token file at $TOKEN_FILE"; exit 1; }
set -a; . "$TOKEN_FILE"; set +a
[[ -r "$GUARD" ]] || { warn "no safety guard at $GUARD — refusing to continue"; exit 1; }
# shellcheck source=/dev/null
. "$GUARD"

PROTECTED_IDS="$(do_protected_ids)" || exit 1
PROTECTED_COUNT=$(printf '%s\n' "$PROTECTED_IDS" | grep -c . || true)

ACCOUNT_JSON=$(api GET /account)
DROPLET_LIMIT=$(jqp 'a=json.load(sys.stdin)["account"];print(a["droplet_limit"])' <<<"$ACCOUNT_JSON")
LIVE_JSON=$(api GET "/droplets?per_page=200")
LIVE_COUNT=$(jqp 'print(len(json.load(sys.stdin)["droplets"]))' <<<"$LIVE_JSON")
LIVE_IDS=$(jqp 'print("\n".join(str(d["id"]) for d in json.load(sys.stdin)["droplets"]))' <<<"$LIVE_JSON")

say "protected baseline : $PROTECTED_COUNT Droplet(s) — never touched"
say "live on account    : $LIVE_COUNT Droplet(s)"
say "account limit      : $DROPLET_LIMIT"

if [[ "$LIVE_COUNT" != "$PROTECTED_COUNT" ]]; then
  printf '\n'
  warn "live count ($LIVE_COUNT) does not match the baseline ($PROTECTED_COUNT)."
  warn "Something exists that this wizard did not create, or a past run leaked a"
  warn "Droplet. STOP and reconcile by hand before creating anything."
  exit 1
fi
while read -r id; do
  [[ -n "$id" ]] || continue
  grep -qx "$id" <<<"$PROTECTED_IDS" || { warn "unknown Droplet $id on account — stop and ask"; exit 1; }
done <<<"$LIVE_IDS"

FREE_SLOTS=$(( DROPLET_LIMIT - LIVE_COUNT ))
printf '\n'
say "Free slots: $FREE_SLOTS. This wizard uses exactly one, and gives it back."
[[ "$FREE_SLOTS" -ge 1 ]] || { warn "no free slot — cannot continue"; exit 1; }
pause "Baseline verified. Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Choose the region and plan"
say "DigitalOcean has no Japan region. Its only Asia-Pacific regions are:"
printf '\n'
step "sgp1  Singapore  — closest to China Telecom, best route odds"
step "blr1  Bangalore"
step "syd1  Sydney"
printf '\n'
warn "Whatever this measures is NOT Tokyo route evidence. It is a rehearsal of"
warn "provisioning, tunnelling and measurement tooling. Do not file the result"
warn "against the Tokyo route gate."
printf '\n'
ask DO_REGION "Region [sgp1]:"; DO_REGION="${DO_REGION:-sgp1}"
say "Plans available in that region under the USD 20 ceiling:"
step "s-2vcpu-2gb  2 vCPU / 2 GB / 3 TB   \$18/mo  \$0.02679/hr   ← recommended"
step "s-1vcpu-2gb  1 vCPU / 2 GB / 2 TB   \$12/mo  \$0.01786/hr"
step "s-1vcpu-1gb  1 vCPU / 1 GB / 1 TB    \$6/mo  \$0.00893/hr"
printf '\n'
ask DO_SIZE "Plan [s-2vcpu-2gb]:"; DO_SIZE="${DO_SIZE:-s-2vcpu-2gb}"
ask DO_IMAGE "Image [ubuntu-24-04-x64]:"; DO_IMAGE="${DO_IMAGE:-ubuntu-24-04-x64}"
write_env DO_REGION "$DO_REGION"
write_env DO_SIZE "$DO_SIZE"
write_env DO_IMAGE "$DO_IMAGE"
printf '\n'
note "Billing is hourly. A 4-hour cycle on s-2vcpu-2gb costs about USD 0.11."
note "A powered-off Droplet still bills. This wizard destroys, never stops."
pause "Press Enter."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Dedicated SSH key"
say "A key used only for this experiment, kept outside the repository."
printf '\n'
if [[ -f "$SSH_KEY" ]]; then
  say "Reusing existing key: $SSH_KEY"
else
  ssh-keygen -t ed25519 -N "" -C "vpn-gcore-experiment" -f "$SSH_KEY" >/dev/null
  say "Generated $SSH_KEY (mode 600)."
fi
chmod 600 "$SSH_KEY"
PUBKEY="$(cat "${SSH_KEY}.pub")"
FPR="$(ssh-keygen -lf "${SSH_KEY}.pub" | awk '{print $2}')"

KEY_ID=$(api GET "/account/keys?per_page=200" | jqp '
keys = json.load(sys.stdin)["ssh_keys"]
pub = open(sys.argv[1]).read().split()[1]
for k in keys:
    if k["public_key"].split()[1] == pub:
        print(k["id"]); break
' "${SSH_KEY}.pub")
if [[ -z "$KEY_ID" ]]; then
  KEY_ID=$(api POST /account/keys "$(python3 -c '
import json,sys
print(json.dumps({"name":"vpn-gcore-experiment","public_key":sys.argv[1]}))' "$PUBKEY")" \
    | jqp 'print(json.load(sys.stdin)["ssh_key"]["id"])')
  say "Uploaded the public key to DigitalOcean as key id $KEY_ID."
else
  say "Public key already registered as key id $KEY_ID."
fi
write_env DO_SSH_KEY_ID "$KEY_ID"
pause "Press Enter."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Create exactly one Droplet"
DROPLET_NAME="vpn-gcore-exp-$(date +%Y%m%d-%H%M)"
say "About to create:"
printf '\n'
step "name    $DROPLET_NAME"
step "region  $DO_REGION"
step "plan    $DO_SIZE"
step "image   $DO_IMAGE"
step "tag     $TAG   (this tag is what makes it destroyable)"
step "extras  IPv6 on, monitoring on, backups off"
printf '\n'
warn "This consumes the account's last free Droplet slot and starts billing."
confirm "Create it?" || { say "Nothing created."; exit 0; }

# Take the guard's tagged payload, then add the measurement server bootstrap.
BASE_PAYLOAD=$(do_create_droplet_payload "$DROPLET_NAME" "$DO_REGION" "$DO_SIZE" "$DO_IMAGE" "$KEY_ID")
USER_DATA=$(cat <<'CLOUDINIT'
#!/bin/bash
set -eux
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y nginx iperf3
head -c 104857600 /dev/urandom > /var/www/html/100MB.bin
printf 'server {\n listen 443 default_server;\n listen [::]:443 default_server;\n root /var/www/html;\n}\n' > /etc/nginx/sites-available/tcp443
ln -sf /etc/nginx/sites-available/tcp443 /etc/nginx/sites-enabled/tcp443
systemctl enable --now nginx
printf '[Unit]\nDescription=iperf3\n[Service]\nExecStart=/usr/bin/iperf3 -s\nRestart=always\n[Install]\nWantedBy=multi-user.target\n' > /etc/systemd/system/iperf3.service
systemctl daemon-reload
systemctl enable --now iperf3
touch /var/lib/vpn-gcore-ready
CLOUDINIT
)
PAYLOAD=$(python3 -c '
import json,sys
p=json.loads(sys.argv[1]); p["user_data"]=sys.argv[2]
assert "vpn-gcore-experiment" in p["tags"], "guard tag missing"
print(json.dumps(p))' "$BASE_PAYLOAD" "$USER_DATA")

CREATE_JSON=$(api POST /droplets "$PAYLOAD")
DROPLET_ID=$(jqp 'print(json.load(sys.stdin)["droplet"]["id"])' <<<"$CREATE_JSON" 2>/dev/null || true)
if [[ -z "$DROPLET_ID" ]]; then
  warn "create failed — response saved to $RUN_DIR/create-error.json"
  printf '%s' "$CREATE_JSON" > "$RUN_DIR/create-error.json"
  warn "Check the dashboard for an orphan before re-running; the slot may be held."
  exit 1
fi
write_env DO_DROPLET_ID "$DROPLET_ID"
say "Created Droplet id $DROPLET_ID. Waiting for an address and for boot…"

DROPLET_IP=""
for _ in $(seq 1 60); do
  D=$(api GET "/droplets/$DROPLET_ID")
  DROPLET_IP=$(jqp '
import json,sys
d=json.load(sys.stdin)["droplet"]
v4=[n["ip_address"] for n in d["networks"]["v4"] if n["type"]=="public"]
print(v4[0] if v4 and d["status"]=="active" else "")' <<<"$D")
  [[ -n "$DROPLET_IP" ]] && break
  sleep 10
done
[[ -n "$DROPLET_IP" ]] || { warn "Droplet never became active. Destroy it in Stage 8."; }
write_env DO_DROPLET_IP "$DROPLET_IP"
say "Address assigned. It is stored in $ENV_FILE and never printed to a public place."
note "The bootstrap installs nginx and iperf3; give it about two minutes."
pause "Press Enter once you are ready to switch networks."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Turn the commercial VPN OFF"
warn "Everything measured from here must run on the bare China Telecom path."
warn "A measurement taken through the commercial VPN is a different experiment"
warn "and must never be recorded as direct-route evidence."
printf '\n'
step "Quit Shadowrocket / any other VPN client completely."
step "Confirm the laptop is tethered to the China Telecom 5G handset in Hangzhou."
step "Pause downloads, cloud backups and OS updates. Keep the handset still."
printf '\n'
pause "Press Enter when the VPN is fully off."

while true; do
  printf '\n'
  say "Checking the live path…"
  FAKE_DNS=$(dig +short +time=3 +tries=1 example.com 2>/dev/null | grep -c '^198\.18\.' || true)
  ORG=$(curl -4 -sS --max-time 10 https://ipinfo.io/org 2>/dev/null || echo unknown)
  CITY=$(curl -4 -sS --max-time 10 https://ipinfo.io/city 2>/dev/null || echo unknown)
  CC=$(curl -4 -sS --max-time 10 https://ipinfo.io/country 2>/dev/null || echo unknown)
  if [[ -z "$CC" || "$CC" == unknown ]]; then   # ipinfo itself may be unreachable from CN
    CC=$(curl -4 -sS --max-time 10 https://api.country.is 2>/dev/null \
         | jqp 'print(json.load(sys.stdin).get("country","unknown"))' 2>/dev/null || echo unknown)
    [[ "$CC" == unknown ]] || note "ipinfo.io unreachable; fell back to api.country.is"
  fi
  say "resolver  : $( [[ "$FAKE_DNS" -gt 0 ]] && echo 'FAKE-IP 198.18/15 — a tunnel is still capturing DNS' || echo 'clean' )"
  say "public org: $ORG"
  say "location  : $CITY / $CC"
  printf '\n'

  if [[ "$FAKE_DNS" -gt 0 ]]; then
    warn "A VPN or proxy is still intercepting DNS. Turn it fully off."
  elif printf '%s' "$ORG$CC" | grep -Eqi 'gcore|g-core|akamai|linode|vultr|digitalocean|datacamp|m247|JP$'; then
    warn "The visible exit looks like a datacenter or a Japan exit, not China Telecom."
  elif [[ "$CC" == "CN" ]]; then
    say "Path looks like the bare China Telecom access network."
    { echo "vpn_state=off"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=verified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    break
  else
    warn "Country reads '$CC', expected CN."
    note "Both geolocation services being unreachable is itself plausible on bare"
    note "China Telecom and is not by itself evidence that a VPN is still up."
  fi

  # A clean resolver is the load-bearing check; geolocation is corroboration and
  # may simply be blocked. Allow the operator to vouch, but record that they did.
  printf '\n'
  if [[ "$FAKE_DNS" -eq 0 ]] \
     && confirm "Override: VPN is off and this is China Telecom 5G in Hangzhou. Proceed?"; then
    { echo "vpn_state=off-operator-confirmed"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=unverified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    warn "Recorded as operator-confirmed with unverified geolocation."
    break
  fi
  confirm "Re-check?" || { warn "Refusing to measure through a tunnel."; exit 1; }
done
ask SESSION_KIND "Session kind — off-peak or peak [off-peak]:"
SESSION_KIND="${SESSION_KIND:-off-peak}"
echo "session_kind=$SESSION_KIND" >> "$RUN_DIR/path-state.txt"
pause "Press Enter to start measuring."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Measure the raw route to the exit node"
set -a; . "$ENV_FILE"; set +a
say "Target: the Droplet created in Stage 4. Output folder: $RUN_DIR"
say "This takes roughly 15 minutes. Leave the handset alone."
printf '\n'

capture "control-start-ping-cloudflare" ping -c 100 1.1.1.1
capture "node-ping-100"                 ping -c 100 "$DROPLET_IP"
capture "node-traceroute-icmp"          traceroute -I -q 3 "$DROPLET_IP"
capture "node-traceroute-tcp443"        traceroute -P TCP -p 443 -q 3 "$DROPLET_IP"
capture "node-tcp443-connect"           curl -4 -sS -o /dev/null -m 20 \
  -w 'connect=%{time_connect}s total=%{time_total}s code=%{http_code}\n' "http://$DROPLET_IP:443/"

for i in 1 2 3; do
  capture "node-download-100mb-$i" curl -4 -L -o /dev/null -sS --max-time 300 \
    -w 'code=%{http_code} bytes=%{size_download} time=%{time_total}s speed=%{speed_download}B/s\n' \
    "http://$DROPLET_IP/100MB.bin"
  sleep 10
done

if command -v iperf3 >/dev/null 2>&1; then
  capture "node-iperf3-down" iperf3 -c "$DROPLET_IP" -R -t 30 -P 4
  capture "node-iperf3-up"   iperf3 -c "$DROPLET_IP"    -t 30 -P 4
else
  note "iperf3 missing locally — install it for the upload direction (brew install iperf3)."
fi

say "Now a 30-minute continuous latency run to expose bursts of loss."
if confirm "Run it?"; then
  capture "node-continuous-30min" ping -c 1800 "$DROPLET_IP"
fi
capture "control-end-ping-cloudflare" ping -c 100 1.1.1.1
say "Raw output written to $RUN_DIR"
pause "Press Enter."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Record the result"
RESULT="$RUN_DIR/result.md"
{
  echo "# Candidate result: DigitalOcean $DO_SIZE in $DO_REGION"
  echo
  echo "> NOT Tokyo route evidence. DigitalOcean operates no Japan region."
  echo "> This is a tooling rehearsal only. See docs/adr/0002."
  echo
  cat "$RUN_DIR/path-state.txt"
  echo
  echo "Raw captures: $RUN_DIR"
  echo
  sed -n '/^## Candidate$/,$p' "$REPO_ROOT/docs/benchmark-protocol.md" 2>/dev/null \
    || echo "Fill in from the result template in docs/benchmark-protocol.md."
} > "$RESULT"
say "Pre-filled result template: $RESULT"
step "Fill in the measured values from the capture files."
step "Keep it in /private/tmp. Sanitize before anything reaches an issue."
warn "Never paste the Droplet address into GitHub."
pause "Press Enter when you are done reading."

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Destroy the Droplet and give the slot back"
say "The exit node is billed until destroyed. Powering it off does not help."
printf '\n'
say "Destroying Droplet id $DROPLET_ID via the guard, which refuses any target"
say "that is on the protected baseline or missing the '$TAG' tag."
printf '\n'
note "You will be asked to type the Droplet name: $DROPLET_NAME"
printf '\n'
if do_destroy_droplet "$DROPLET_ID"; then
  sleep 15
  AFTER=$(api GET "/droplets?per_page=200" | jqp 'print(len(json.load(sys.stdin)["droplets"]))')
  if [[ "$AFTER" == "$PROTECTED_COUNT" ]]; then
    say "Account is back to its protected baseline of $PROTECTED_COUNT Droplet(s)."
  else
    warn "Account shows $AFTER Droplet(s), expected $PROTECTED_COUNT. Check by hand."
  fi
  say "Also confirm no reserved IP or volume was left behind:"
  step "https://cloud.digitalocean.com/networking/reserved_ips"
  step "https://cloud.digitalocean.com/volumes"
else
  warn "NOT destroyed. It is still billing. Destroy it before you stop for the day:"
  note "  set -a; . $TOKEN_FILE; set +a; . $GUARD; do_destroy_droplet $DROPLET_ID"
fi
printf '\n'
note "To test another region, re-run this wizard and choose blr1 or syd1."
note "Turn the commercial VPN back on when you are finished."

finish
