#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — screen every DigitalOcean region from the bare China Telecom path,
# before renting anything. No cloud resources, no cost, no API token.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# DigitalOcean's legacy speedtest-<region>.digitalocean.com hosts are gone
# (re-confirmed NXDOMAIN on 2026-09-02), which is why ADR 0002 says renting is
# the only way to measure. It is not: many regions run a Spaces endpoint on
# DigitalOcean's own network. The original ten targets were verified on
# 2026-09-02 as AS14061 and physically in their named regions. New targets
# still need the same verification; nyc1 and nyc2 currently do not resolve.
#
# Caveat, and it matters: a Spaces endpoint is not a Droplet. It may sit on a
# different prefix with different transit inside the same region. Treat this as
# a screening signal, exactly like every other provider's test host, not as
# proof of a Droplet's route. The list follows the live regions API. A region
# without a matching Spaces endpoint is recorded as skipped.
REGIONS=(
  "nyc1 NewYork1"
  "nyc2 NewYork2"
  "nyc3 NewYork3"
  "atl1 Atlanta"
  "ric1 Richmond"
  "mkc1 KansasCity"
  "mem1 Memphis"
  "sgp1 Singapore"
  "blr1 Bangalore"
  "syd1 Sydney"
  "sfo3 SanFrancisco"
  "sfo2 SanFrancisco2"
  "tor1 Toronto"
  "lon1 London"
  "ams3 Amsterdam"
  "fra1 Frankfurt"
)

ENV_FILE="/private/tmp/vpn-gcore-do-screen.env"
RUN_DIR="/private/tmp/vpn-gcore-do-screen-$(date +%Y%m%d-%H%M%S)"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# What sfo2 delivered from a rented Droplet, for comparison.
# Run folder /private/tmp/vpn-gcore-do-stage2-20260902-064513.
REF_REGION="sfo2"
REF_RTT=154
REF_UPLOAD="20.5 Mbit/s with 3019 retransmits"

umask 077
mkdir -p "$RUN_DIR"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

# shellcheck source=scripts/proof-lifecycle.sh
. "$REPO_ROOT/scripts/proof-lifecycle.sh"

jqp() { local prog="$1"; shift; python3 -c "import json,sys
$prog" "$@"; }

capture() {
  proof_capture "$RUN_DIR" "$@"
}

SCREEN_FAILED=0
screen_capture() {
  if ! capture "$@"; then
    SCREEN_FAILED=1
  fi
}

banner "DigitalOcean region screen — measure before you rent"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — local only"
say "This screens every current DigitalOcean region from this connection."
say "It creates nothing, spends nothing, and needs no API token."
printf '\n'
say "Output folder: $RUN_DIR"
printf '\n'
MISSING=0
for tool in curl python3 ping traceroute dig; do
  if command -v "$tool" >/dev/null 2>&1; then
    step "found $tool"
  else
    warn "missing: $tool"; MISSING=1
  fi
done
[[ "$MISSING" -eq 0 ]] || { printf '\n'; warn "install the missing tools and re-run"; exit 1; }
printf '\n'
note "Takes roughly 20 minutes. Sixteen regions, 100 pings and a trace each."
printf '\n'
pause "Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Turn the commercial VPN OFF"
warn "Screening through the commercial VPN measures Gcore Tokyo, not China"
warn "Telecom. Every number here must come from the bare path."
printf '\n'
step "Quit Shadowrocket / any other VPN client completely."
step "Confirm the laptop is tethered to the China Telecom 5G handset in Hangzhou."
step "Pause downloads, cloud backups and OS updates. Keep the handset still."
printf '\n'
pause "Press Enter when the VPN is fully off."

while true; do
  printf '\n'
  say "Checking the live path…"
  FAKE_DNS=$(dig +short +time=3 +tries=1 example.com 2>/dev/null | grep -c '^198\.18\.' || true)
  ORG=$(curl -4 -sS --max-time 10 https://ipinfo.io/org 2>/dev/null || echo unknown)
  CITY=$(curl -4 -sS --max-time 10 https://ipinfo.io/city 2>/dev/null || echo unknown)
  CC=$(curl -4 -sS --max-time 10 https://ipinfo.io/country 2>/dev/null || echo unknown)
  if [[ -z "$CC" || "$CC" == unknown ]]; then
    CC=$(curl -4 -sS --max-time 10 https://api.country.is 2>/dev/null \
         | jqp 'print(json.load(sys.stdin).get("country","unknown"))' 2>/dev/null || echo unknown)
    [[ "$CC" == unknown ]] || note "ipinfo.io unreachable; fell back to api.country.is"
  fi
  say "resolver  : $( [[ "$FAKE_DNS" -gt 0 ]] && echo 'FAKE-IP 198.18/15 — a tunnel is still capturing DNS' || echo 'clean' )"
  say "public org: $ORG"
  say "location  : $CITY / $CC"
  printf '\n'

  if [[ "$FAKE_DNS" -gt 0 ]]; then
    warn "A VPN or proxy is still intercepting DNS. Turn it fully off."
  elif printf '%s' "$ORG$CC" | grep -Eqi 'gcore|g-core|akamai|linode|vultr|digitalocean|datacamp|m247|JP$'; then
    warn "The visible exit looks like a datacenter or a Japan exit, not China Telecom."
  elif [[ "$CC" == "CN" ]]; then
    say "Path looks like the bare China Telecom access network."
    { echo "vpn_state=off"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=verified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    break
  else
    warn "Country reads '$CC', expected CN."
    note "Both geolocation services being unreachable is itself plausible on bare"
    note "China Telecom and is not by itself evidence that a VPN is still up."
  fi

  printf '\n'
  if [[ "$FAKE_DNS" -eq 0 ]] \
     && confirm "Override: VPN is off and this is China Telecom 5G in Hangzhou. Proceed?"; then
    { echo "vpn_state=off-operator-confirmed"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
      echo "geolocation=unverified"
      echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
    warn "Recorded as operator-confirmed with unverified geolocation."
    break
  fi
  confirm "Re-check?" || { warn "Refusing to measure through a tunnel."; exit 1; }
done
ask SESSION_KIND "Session kind — off-peak or peak [off-peak]:"
SESSION_KIND="${SESSION_KIND:-off-peak}"
echo "session_kind=$SESSION_KIND" >> "$RUN_DIR/path-state.txt"
write_env SESSION_KIND "$SESSION_KIND"
pause "Press Enter to start screening."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Screen all current regions"
say "Same control target and ping count as the exit-node runs, so the numbers"
say "compare directly across sessions."
printf '\n'

screen_capture "control-start-ping-cloudflare" ping -c 100 -i 0.3 1.1.1.1
printf '\n'

for entry in "${REGIONS[@]}"; do
  slug="${entry%% *}"; label="${entry##* }"
  host="${slug}.digitaloceanspaces.com"
  ip=$(dig +short +time=5 +tries=2 "$host" 2>/dev/null | grep -E '^[0-9]+\.' | head -1)
  if [[ -z "$ip" ]]; then
    warn "$slug ($label): could not resolve $host — skipped"
    echo "$slug unresolved" >> "$RUN_DIR/skipped.txt"
    continue
  fi
  say "$slug ($label) → $ip"
  echo "$slug $ip $host" >> "$RUN_DIR/targets.txt"
  screen_capture "$slug-ping-100"        ping -c 100 -i 0.3 "$ip"
  screen_capture "$slug-traceroute-icmp" traceroute -I -q 1 -m 20 -w 2 "$ip"
  screen_capture "$slug-tcp443-connect"  curl -4 -sS -o /dev/null -m 20 \
    -w 'connect=%{time_connect}s tls=%{time_appconnect}s total=%{time_total}s code=%{http_code}\n' \
    "https://$host/"
done

printf '\n'
screen_capture "control-end-ping-cloudflare" ping -c 100 -i 0.3 1.1.1.1
if [[ "$SCREEN_FAILED" -ne 0 ]]; then
  warn "One or more screen probes failed; review exit_code lines before ranking."
fi
printf '\n'
pause "Press Enter for the ranking."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Ranking — which region to rent"
python3 - "$RUN_DIR" "$REF_REGION" "$REF_RTT" "$REF_UPLOAD" > "$RUN_DIR/ranking.md" <<'PY'
import glob, os, re, statistics as st, sys

run_dir, ref_region, ref_rtt, ref_upload = sys.argv[1], sys.argv[2], float(sys.argv[3]), sys.argv[4]

def ping_stats(path):
    try:
        raw = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return None
    times = [float(x) for x in re.findall(r'time=([\d.]+) ms', raw)]
    m = re.search(r'([\d.]+)% packet loss', raw)
    loss = float(m.group(1)) if m else None
    if not times or loss is None:
        return None
    ranked = sorted(times)
    p95 = ranked[min(len(ranked) - 1, int(round(0.95 * (len(ranked) - 1))))]
    jitter = st.mean(abs(b - a) for a, b in zip(times, times[1:])) if len(times) > 1 else 0.0
    return dict(n=len(times), min=ranked[0], med=st.median(ranked), avg=st.mean(times),
                p95=p95, max=ranked[-1], jitter=jitter, loss=loss)

def hops(path):
    """Count responding hops and note whether the target answered."""
    try:
        raw = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return None
    return len([l for l in raw.splitlines() if re.match(r'\s*\d+\s+\S', l)])

out = []
w = out.append
w("# DigitalOcean region screen\n")
ps = os.path.join(run_dir, "path-state.txt")
if os.path.exists(ps):
    for line in open(ps, encoding="utf-8"):
        w("    " + line.rstrip())
    w("")
w("Raw captures: %s\n" % run_dir)

w("> Probes are each region's Spaces endpoint (AS14061, in-region), not a")
w("> Droplet. Same prefix is not guaranteed, so this ranks routes, it does not")
w("> prove a Droplet's route. It also cannot measure upload; only renting can.\n")

cs = ping_stats(os.path.join(run_dir, "control-start-ping-cloudflare.txt"))
ce = ping_stats(os.path.join(run_dir, "control-end-ping-cloudflare.txt"))
if cs and ce:
    w("## Controls (1.1.1.1)\n")
    w("| control | median ms | avg ms | loss % |")
    w("|---|---|---|---|")
    w("| start | %.1f | %.1f | %.1f |" % (cs["med"], cs["avg"], cs["loss"]))
    w("| end   | %.1f | %.1f | %.1f |" % (ce["med"], ce["avg"], ce["loss"]))
    drift = abs(cs["med"] - ce["med"])
    w("")
    if drift > 20:
        w("Controls disagree by %.1f ms on median. Radio conditions moved during" % drift)
        w("the run, so treat the region comparison below as weak.")
    else:
        w("Controls agree within %.1f ms, so the regions below are comparable." % drift)
    w("")

rows = []
tf = os.path.join(run_dir, "targets.txt")
slugs = [l.split()[0] for l in open(tf, encoding="utf-8")] if os.path.exists(tf) else []
for slug in slugs:
    s = ping_stats(os.path.join(run_dir, "%s-ping-100.txt" % slug))
    if s:
        s["slug"] = slug
        s["hops"] = hops(os.path.join(run_dir, "%s-traceroute-icmp.txt" % slug)) or 0
        rows.append(s)

if not rows:
    w("## Result: INCONCLUSIVE\n")
    w("No region produced usable ping data. Check the raw files.")
    print("\n".join(out))
    raise SystemExit(0)

# Loss first, then tail latency. A route that drops packets during the usage
# window is not the better candidate even if its median looks good.
rows.sort(key=lambda r: (r["loss"], r["p95"]))

w("## Regions, best first\n")
w("| region | loss % | min | median | avg | p95 | max | jitter | hops |")
w("|---|---|---|---|---|---|---|---|---|")
for r in rows:
    w("| %s | %.1f | %.0f | %.0f | %.0f | %.0f | %.0f | %.1f | %d |" % (
        r["slug"], r["loss"], r["min"], r["med"], r["avg"], r["p95"], r["max"],
        r["jitter"], r["hops"]))
w("")

best = rows[0]
ref = next((r for r in rows if r["slug"] == ref_region), None)

w("## Recommendation\n")
w("Best route: **%s** at %.0f ms median, %.0f ms p95, %.1f%% loss.\n"
  % (best["slug"], best["med"], best["p95"], best["loss"]))

if ref:
    w("For comparison, %s screens at %.0f ms median and %.1f%% loss here, and a"
      % (ref_region, ref["med"], ref["loss"]))
    w("real Droplet there measured %.0f ms and %s.\n" % (ref_rtt, ref_upload))
    if best["slug"] == ref_region:
        w("**%s is still the best DigitalOcean route from this connection.**" % ref_region)
        w("Spend the next paid cycle on its tunnel and peak-hour gate, not on")
        w("another off-peak regional comparison.")
    else:
        gain = ref["med"] - best["med"]
        w("**%s beats %s by %.0f ms on median and %.1f points of loss.**"
          % (best["slug"], ref_region, gain, ref["loss"] - best["loss"]))
        w("")
        w("This is a free-screen signal only. Repeat it during a valid peak")
        w("window before considering a paid cycle. A Droplet must still beat")
        w("the %s sfo2 upload result or add clear failover value." % ref_upload.split()[0])
else:
    w("No %s data in this run, so there is no baseline to compare against." % ref_region)

w("")
w("## Scope\n")
w("None of this is Tokyo evidence. DigitalOcean has no Japan region. Under")
w("ADR 0003, sfo2 is the primary San Francisco candidate; other regions must")
w("beat it on peak stability or provide a clear failover benefit.")

print("\n".join(out))
PY

cat "$RUN_DIR/ranking.md"
printf '\n'
say "Ranking written to $RUN_DIR/ranking.md"
note "Nothing was created and nothing is billing."
note "Turn the commercial VPN back on when you are finished."

finish
