#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
err()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  # ENV_FILE is later re-read with `set -a; . "$ENV_FILE"`, so a value with a
  # space or a metacharacter would execute as a command in a shell that is
  # holding a live API token. Every legitimate value here is a slug, an id, an
  # address, or a path.
  if [[ -z "$value" || "$value" =~ [^A-Za-z0-9_.:@/-] ]]; then
    warn "refusing to store an unsafe value for $key"
    exit 1
  fi
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one create → test → destroy cycle against one DigitalOcean region.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Everything this wizard captures is either a live public address or an account
# identifier, so it never touches the repository. Private, mode 600, outside.
ENV_FILE="/private/tmp/vpn-gcore-do-run.env"
TOKEN_FILE="/private/tmp/vpn-gcore-do-session.env"
SSH_KEY="/private/tmp/vpn-gcore-do-experiment-key"
EXISTING_RUN_DIR=$(grep -E '^DO_RUN_DIR=' "$ENV_FILE" 2>/dev/null | tail -n1 | cut -d= -f2- || true)
RUN_DIR="${DO_RUN_DIR:-${EXISTING_RUN_DIR:-/private/tmp/vpn-gcore-do-stage2-$(date +%Y%m%d-%H%M%S)}}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GUARD="$REPO_ROOT/scripts/do-guard.sh"
PROTECTED_IDS_FILE="${DO_PROTECTED_IDS:-/private/tmp/vpn-gcore-do-discovery/protected-ids.txt}"
API="https://api.digitalocean.com/v2"
MAX_PROOF_BUDGET_USD=5
MAX_PROOF_LIFECYCLE_DAYS=7
XRAY_VERSION="v26.6.1"

# shellcheck source=scripts/proof-lifecycle.sh
. "$REPO_ROOT/scripts/proof-lifecycle.sh"

# One literal for the ownership tag. The guard, the create payload, the recorded
# state, and every destroy check all read it from here.
TAG="$PROOF_TAG"

umask 077
mkdir -p "$RUN_DIR"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"
if [[ -z "$EXISTING_RUN_DIR" ]]; then
  write_env DO_RUN_DIR "$RUN_DIR"
fi

api() { # api METHOD PATH [JSON-BODY]
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -sS -m 60 -X "$method" \
      -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
      -H "Content-Type: application/json" -d "$body" "$API$path"
  else
    curl -sS -m 60 -X "$method" \
      -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" "$API$path"
  fi
}

jqp() { local prog="$1"; shift; python3 -c "import json,sys
$prog" "$@"; }  # tiny json helper, no jq

capture() {
  proof_capture "$RUN_DIR" "$@"
}

MEASUREMENT_FAILED=0
run_measurement() {
  if ! capture "$@"; then
    MEASUREMENT_FAILED=1
  fi
}

# A Droplet bills from the moment it exists, and this script has many ways to
# stop early — a declined prompt, a failed guard, an unexpected non-zero under
# `set -e`. Whatever the exit path, the operator leaves with the exact command
# that gives the slot back.
PROOF_LIVE_DROPLET_ID=""
proof_exit_reminder() {
  local status=$?
  if [[ -n "$PROOF_LIVE_DROPLET_ID" ]]; then
    printf '\n'
    err "Droplet $PROOF_LIVE_DROPLET_ID still exists and is STILL BILLING."
    err "Destroy it before you stop for the day:"
    note "  cd $REPO_ROOT"
    note "  set -a; . $TOKEN_FILE; set +a; . $GUARD; do_destroy_droplet $PROOF_LIVE_DROPLET_ID"
  fi
  return "$status"
}
trap proof_exit_reminder EXIT

# authorize ACTION PROMPT — ask the human, and let their answer be the only
# thing that sets the cloud-mutation flag. Never hardcode PROOF_CLOUD_AUTHORIZED
# at a call site: that would make the gate decorative.
authorize() {
  local action="$1" prompt="$2" granted=0
  if [[ "${PROOF_DRY_RUN:-0}" == 1 ]]; then
    proof_require_mutation_authorized "$action"
    return
  fi
  if confirm "$prompt"; then
    granted=1
  fi
  PROOF_CLOUD_AUTHORIZED="$granted" proof_require_mutation_authorized "$action"
}

banner "DigitalOcean exit-node route test — create, measure, destroy"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — protected baseline must be intact"
say "This account holds Droplets belonging to unrelated projects. Before any"
say "write call we re-verify the baseline and fail closed if it moved."
printf '\n'

for tool in curl python3 ssh ssh-keygen ping traceroute dig; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing required tool: $tool"; exit 1; }
done
command -v iperf3 >/dev/null 2>&1 || note "iperf3 not installed locally — bidirectional test will be skipped"

[[ -r "$TOKEN_FILE" ]] || { warn "no token file at $TOKEN_FILE"; exit 1; }
set -a
# shellcheck source=/dev/null  # private, mode-600, outside the repository
. "$TOKEN_FILE"
set +a
[[ -r "$GUARD" ]] || { warn "no safety guard at $GUARD — refusing to continue"; exit 1; }
[[ -s "$PROTECTED_IDS_FILE" ]] || {
  warn "no protected baseline at $PROTECTED_IDS_FILE — refusing to continue"
  warn "Capture the baseline before any write call. See docs/agents/infrastructure-safety.md."
  exit 1
}
DO_PROTECTED_IDS="$PROTECTED_IDS_FILE"
# shellcheck disable=SC2034  # consumed by do-guard.sh while it is sourced below
DO_EXPERIMENT_TAG="$TAG"
# shellcheck source=scripts/do-guard.sh
. "$GUARD"

PROTECTED_IDS="$(do_protected_ids)" || exit 1
PROTECTED_COUNT=$(printf '%s\n' "$PROTECTED_IDS" | grep -c . || true)

ACCOUNT_JSON=$(api GET /account)
DROPLET_LIMIT=$(jqp 'a=json.load(sys.stdin)["account"];print(a["droplet_limit"])' <<<"$ACCOUNT_JSON")
LIVE_JSON=$(api GET "/droplets?per_page=200")
LIVE_COUNT=$(jqp 'print(len(json.load(sys.stdin)["droplets"]))' <<<"$LIVE_JSON")
LIVE_IDS=$(jqp 'print("\n".join(str(d["id"]) for d in json.load(sys.stdin)["droplets"]))' <<<"$LIVE_JSON")
printf '%s\n' "$PROTECTED_IDS" > "$RUN_DIR/protected-ids.txt"
printf '%s\n' "$LIVE_JSON" > "$RUN_DIR/baseline-live-droplets.json"

say "protected baseline : $PROTECTED_COUNT Droplet(s) — never touched"
say "live on account    : $LIVE_COUNT Droplet(s)"
say "account limit      : $DROPLET_LIMIT"

EXISTING_DROPLET_ID="$(_existing DO_DROPLET_ID || true)"
if [[ -n "$EXISTING_DROPLET_ID" ]]; then
  warn "A previous proof lifecycle is recorded in $ENV_FILE."
  api GET "/droplets/$EXISTING_DROPLET_ID" > "$RUN_DIR/recovery-droplet.json" || true
  if [[ -f "$RUN_DIR/state.json" ]] \
     && proof_recovery_plan "$RUN_DIR/state.json" "$RUN_DIR/protected-ids.txt" "$RUN_DIR/recovery-droplet.json"; then
    warn "Stop here and finish the exact recorded lifecycle before creating another proof node."
    note "  cd $REPO_ROOT"
    note "  set -a; . $TOKEN_FILE; set +a; . $GUARD; do_destroy_droplet $EXISTING_DROPLET_ID"
  else
    warn "Recovery did not verify exact ownership. Reconcile manually before any mutation."
  fi
  exit 1
fi

if [[ "$LIVE_COUNT" != "$PROTECTED_COUNT" ]]; then
  printf '\n'
  warn "live count ($LIVE_COUNT) does not match the baseline ($PROTECTED_COUNT)."
  warn "Something exists that this wizard did not create, or a past run leaked a"
  warn "Droplet. STOP and reconcile by hand before creating anything."
  exit 1
fi
while read -r id; do
  [[ -n "$id" ]] || continue
  grep -qx "$id" <<<"$PROTECTED_IDS" || { warn "unknown Droplet $id on account — stop and ask"; exit 1; }
done <<<"$LIVE_IDS"

FREE_SLOTS=$(( DROPLET_LIMIT - LIVE_COUNT ))
printf '\n'
say "Free slots: $FREE_SLOTS. This wizard uses exactly one, and gives it back."
[[ "$FREE_SLOTS" -ge 1 ]] || { warn "no free slot — cannot continue"; exit 1; }
pause "Baseline verified. Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Choose the region and plan"
say "Current exit-location candidates:"
printf '\n'
step "sfo2  San Francisco  — primary candidate"
step "sfo3  San Francisco  — same-city replacement candidate"
step "tor1  Toronto        — geographic fallback"
printf '\n'
warn "A DigitalOcean result is never Tokyo evidence. Record it against the"
warn "San Francisco exit-location work in ADR 0003."
printf '\n'
# Both of these are slugs, not menu numbers, and a wrong one is only rejected
# by the API at create time — after the confirmation prompt, and far enough in
# that it reads like a provisioning failure. Validate them here instead.
for _attempt in 1 2 3; do
  ask DO_REGION "Region slug [sfo2]:"; DO_REGION="${DO_REGION:-sfo2}"
  api GET "/regions?per_page=200" | jqp '
regions = json.load(sys.stdin)["regions"]
sys.exit(0 if any(r["slug"] == sys.argv[1] and r["available"] for r in regions) else 1)
' "$DO_REGION" && break
  warn "\"$DO_REGION\" is not an available region slug. Type the slug itself, e.g. sfo2."
  [[ "$_attempt" == 3 ]] && { warn "no valid region after 3 attempts — stopping"; exit 1; }
done

say "Plans available in that region under the USD 20 ceiling:"
step "s-2vcpu-2gb  2 vCPU / 2 GB / 3 TB   \$18/mo  \$0.02679/hr   ← recommended"
step "s-1vcpu-2gb  1 vCPU / 2 GB / 2 TB   \$12/mo  \$0.01786/hr"
step "s-1vcpu-1gb  1 vCPU / 1 GB / 1 TB    \$6/mo  \$0.00893/hr"
note "Type the slug, not the line number."
printf '\n'
DO_PRICE_HOURLY=""
for _attempt in 1 2 3; do
  ask DO_SIZE "Plan slug [s-2vcpu-2gb]:"; DO_SIZE="${DO_SIZE:-s-2vcpu-2gb}"
  # The provider's own hourly price, not a local table, is what the budget guard
  # holds this lifecycle to.
  DO_PRICE_HOURLY=$(api GET "/sizes?per_page=500" | jqp '
sizes = json.load(sys.stdin)["sizes"]
slug, region = sys.argv[1], sys.argv[2]
for s in sizes:
    if s["slug"] != slug:
        continue
    if not s["available"]:
        sys.stderr.write("that plan is not currently available\n"); sys.exit(1)
    if region not in s["regions"]:
        sys.stderr.write("that plan is not offered in %s\n" % region); sys.exit(1)
    sys.stderr.write("%s: USD %s/mo, USD %.5f/hr\n" % (slug, s["price_monthly"], s["price_hourly"]))
    print("%.5f" % s["price_hourly"])
    sys.exit(0)
sys.stderr.write("no such plan slug\n"); sys.exit(1)
' "$DO_SIZE" "$DO_REGION") && break
  warn "\"$DO_SIZE\" is not a usable plan slug in $DO_REGION. Type the slug, e.g. s-2vcpu-2gb."
  [[ "$_attempt" == 3 ]] && { warn "no valid plan after 3 attempts — stopping"; exit 1; }
done

# Region and plan are validated above because a bad slug is only rejected at
# create time. The image slug has exactly the same failure mode.
for _attempt in 1 2 3; do
  ask DO_IMAGE "Image [ubuntu-24-04-x64]:"; DO_IMAGE="${DO_IMAGE:-ubuntu-24-04-x64}"
  api GET "/images?type=distribution&per_page=500" | jqp '
images = json.load(sys.stdin)["images"]
slug, region = sys.argv[1], sys.argv[2]
sys.exit(0 if any(i.get("slug") == slug and region in i.get("regions", []) for i in images) else 1)
' "$DO_IMAGE" "$DO_REGION" && break
  warn "\"$DO_IMAGE\" is not a distribution image available in $DO_REGION."
  [[ "$_attempt" == 3 ]] && { warn "no valid image after 3 attempts — stopping"; exit 1; }
done
write_env DO_REGION "$DO_REGION"
write_env DO_SIZE "$DO_SIZE"
write_env DO_IMAGE "$DO_IMAGE"
proof_init_state "$RUN_DIR" "$DO_REGION" "$DO_SIZE" "$DO_IMAGE" "$MAX_PROOF_BUDGET_USD" "$MAX_PROOF_LIFECYCLE_DAYS" "$XRAY_VERSION" "$DO_PRICE_HOURLY"
printf '\n'
note "Billing is hourly. A 4-hour cycle on s-2vcpu-2gb costs about USD 0.11."
note "This proof lifecycle is bounded to ${MAX_PROOF_LIFECYCLE_DAYS} days and USD ${MAX_PROOF_BUDGET_USD}."
note "A powered-off Droplet still bills. This wizard destroys, never stops."
pause "Press Enter."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Dedicated SSH key"
say "A key used only for this experiment, kept outside the repository."
printf '\n'
if [[ -f "$SSH_KEY" ]]; then
  say "Reusing existing key: $SSH_KEY"
else
  ssh-keygen -t ed25519 -N "" -C "vpn-gcore-experiment" -f "$SSH_KEY" >/dev/null
  say "Generated $SSH_KEY (mode 600)."
fi
chmod 600 "$SSH_KEY"
PUBKEY="$(cat "${SSH_KEY}.pub")"
FPR="$(ssh-keygen -lf "${SSH_KEY}.pub" | awk '{print $2}')"
say "Key fingerprint: $FPR"

KEY_ID=$(api GET "/account/keys?per_page=200" | jqp '
keys = json.load(sys.stdin)["ssh_keys"]
pub = open(sys.argv[1]).read().split()[1]
for k in keys:
    if k["public_key"].split()[1] == pub:
        print(k["id"]); break
' "${SSH_KEY}.pub")
if [[ -z "$KEY_ID" ]]; then
  api GET "/droplets?per_page=200" > "$RUN_DIR/pre-key-live-droplets.json"
  proof_verify_protected_baseline_json "$PROTECTED_IDS" "$RUN_DIR/pre-key-live-droplets.json" \
    || { warn "baseline changed before SSH-key upload — refusing mutation"; exit 1; }
  authorize "upload experiment SSH key" \
    "Upload this experiment public SSH key to the DigitalOcean account?" \
    || { warn "SSH-key upload not authorized; stopping before cloud mutation."; exit 1; }
  KEY_ID=$(api POST /account/keys "$(python3 -c '
import json,sys
print(json.dumps({"name":"vpn-gcore-experiment","public_key":sys.argv[1]}))' "$PUBKEY")" \
    | jqp 'print(json.load(sys.stdin)["ssh_key"]["id"])')
  say "Uploaded the public key to DigitalOcean as key id $KEY_ID."
  write_env DO_SSH_KEY_UPLOADED 1
  proof_record_ssh_key "$RUN_DIR" "$KEY_ID" 1
else
  say "Public key already registered as key id $KEY_ID."
  write_env DO_SSH_KEY_UPLOADED 0
  proof_record_ssh_key "$RUN_DIR" "$KEY_ID" 0
fi
write_env DO_SSH_KEY_ID "$KEY_ID"
pause "Press Enter."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Create exactly one Droplet"
DROPLET_NAME="vpn-gcore-exp-$(date +%Y%m%d-%H%M)"
say "About to create:"
printf '\n'
step "name    $DROPLET_NAME"
step "region  $DO_REGION"
step "plan    $DO_SIZE"
step "image   $DO_IMAGE"
step "tag     $TAG   (this tag is what makes it destroyable)"
step "xray    $XRAY_VERSION  VLESS + REALITY + XTLS Vision on TCP/443"
step "extras  IPv6 on, monitoring on, backups off"
printf '\n'
warn "This consumes the account's last free Droplet slot and starts billing."
api GET "/droplets?per_page=200" > "$RUN_DIR/pre-create-live-droplets.json"
proof_verify_protected_baseline_json "$PROTECTED_IDS" "$RUN_DIR/pre-create-live-droplets.json" \
  || { warn "baseline changed before create — refusing mutation"; exit 1; }
if ! authorize "create Droplet $DROPLET_NAME in $DO_REGION" "Create it?"; then
  say "Nothing created."
  exit 0
fi

# Take the guard's tagged payload, then add the proof-node bootstrap.
BASE_PAYLOAD=$(do_create_droplet_payload "$DROPLET_NAME" "$DO_REGION" "$DO_SIZE" "$DO_IMAGE" "$KEY_ID")
USER_DATA=$(cat <<CLOUDINIT
#!/bin/bash
set -eux
export DEBIAN_FRONTEND=noninteractive
XRAY_VERSION="$XRAY_VERSION"
apt-get update -y
apt-get install -y ca-certificates curl iperf3 openssl ufw
bash -c "\$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --version "\$XRAY_VERSION"
install -d -m 700 /root/vpn-gcore-proof

cat > /etc/sysctl.d/99-vpn-gcore-bbr.conf <<SYSCTL
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
SYSCTL
sysctl --system
tc qdisc replace dev eth0 root fq || true

# Deny by default. Only the three ports this proof actually needs are reachable,
# and iperf3's is useless while its unit is stopped (see below).
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 5201/tcp
ufw --force enable

# The REALITY private key, the client UUID and the short id are generated here.
# Tracing is off across this block so they never reach cloud-init-output.log.
set +x
VLESS_UUID="\$(cat /proc/sys/kernel/random/uuid)"
KEYPAIR="\$(/usr/local/bin/xray x25519)"
REALITY_PRIVATE_KEY="\$(printf '%s\n' "\$KEYPAIR" | awk -F': *' '/Private[[:space:]]*[Kk]ey:/ {print \$2}')"
REALITY_PUBLIC_KEY="\$(printf '%s\n' "\$KEYPAIR" | awk -F': *' '/Public[[:space:]]*[Kk]ey:/ {print \$2}')"
SHORT_ID="\$(openssl rand -hex 8)"
SERVER_NAME="www.apple.com"
TARGET="www.apple.com:443"
PUBLIC_IPV4="\$(curl -4 -sS --max-time 10 https://api.ipify.org || hostname -I | awk '{print \$1}')"
cat > /usr/local/etc/xray/config.json <<XRAY_CONFIG
{
  "log": {
    "loglevel": "warning"
  },
  "policy": {
    "levels": {
      "0": {
        "bufferSize": 4096
      }
    }
  },
  "inbounds": [
    {
      "tag": "vless-reality-proof",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "\$VLESS_UUID",
            "level": 0,
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "\$TARGET",
          "xver": 0,
          "serverNames": [
            "\$SERVER_NAME"
          ],
          "privateKey": "\$REALITY_PRIVATE_KEY",
          "shortIds": [
            "\$SHORT_ID"
          ],
          "fingerprint": "chrome"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ]
}
XRAY_CONFIG
chown nobody:root /usr/local/etc/xray/config.json
chmod 640 /usr/local/etc/xray/config.json
cat > /root/vpn-gcore-proof/shadowrocket-vless-reality.uri <<PROFILE
vless://\$VLESS_UUID@\$PUBLIC_IPV4:443?encryption=none&security=reality&sni=\$SERVER_NAME&fp=chrome&pbk=\$REALITY_PUBLIC_KEY&sid=\$SHORT_ID&type=tcp&flow=xtls-rprx-vision#vpn-gcore-\$XRAY_VERSION-proof
PROFILE
chmod 600 /root/vpn-gcore-proof/shadowrocket-vless-reality.uri
set -x
/usr/local/bin/xray run -test -c /usr/local/etc/xray/config.json
systemctl enable --now xray
systemctl restart xray
# Installed but NOT enabled. An unauthenticated iperf3 server open to the
# internet for the whole lifecycle is a bandwidth-billing hole that the
# compute-hours budget guard cannot see. Stage 6 starts it for the throughput
# runs and stops it again.
printf '[Unit]\nDescription=iperf3\n[Service]\nExecStart=/usr/bin/iperf3 -s\nRestart=always\n' > /etc/systemd/system/iperf3.service
systemctl daemon-reload
systemctl disable iperf3 || true
touch /var/lib/vpn-gcore-ready
CLOUDINIT
)
PAYLOAD=$(python3 -c '
import json,sys
p=json.loads(sys.argv[1]); p["user_data"]=sys.argv[2]
assert "vpn-gcore-experiment" in p["tags"], "guard tag missing"
print(json.dumps(p))' "$BASE_PAYLOAD" "$USER_DATA")

CREATE_JSON=$(api POST /droplets "$PAYLOAD")
DROPLET_ID=$(jqp 'print(json.load(sys.stdin)["droplet"]["id"])' <<<"$CREATE_JSON" 2>/dev/null || true)
if [[ -z "$DROPLET_ID" ]]; then
  warn "create failed — response saved to $RUN_DIR/create-error.json"
  printf '%s' "$CREATE_JSON" > "$RUN_DIR/create-error.json"
  warn "Check the dashboard for an orphan before re-running; the slot may be held."
  exit 1
fi
PROOF_LIVE_DROPLET_ID="$DROPLET_ID"   # from here on, every exit path reminds
write_env DO_DROPLET_ID "$DROPLET_ID"
proof_record_created "$RUN_DIR" "$DROPLET_ID" "$DROPLET_NAME" "$DO_REGION" "$DO_SIZE"
say "Created Droplet id $DROPLET_ID. Waiting for an address and for boot…"

DROPLET_IP=""
for _ in $(seq 1 60); do
  D=$(api GET "/droplets/$DROPLET_ID")
  DROPLET_IP=$(jqp '
import json,sys
d=json.load(sys.stdin)["droplet"]
v4=[n["ip_address"] for n in d["networks"]["v4"] if n["type"]=="public"]
print(v4[0] if v4 and d["status"]=="active" else "")' <<<"$D")
  [[ -n "$DROPLET_IP" ]] && break
  sleep 10
done
NODE_REACHABLE=1
if [[ -z "$DROPLET_IP" ]]; then
  NODE_REACHABLE=0
  warn "Droplet never became active. Skipping Stages 5 and 6; go straight to destroy."
else
  write_env DO_DROPLET_IP "$DROPLET_IP"
  say "Address assigned. It is stored in $ENV_FILE and never printed to a public place."
  note "The bootstrap installs Xray $XRAY_VERSION and iperf3; give it about two minutes."
fi
pause "Press Enter once you are ready to switch networks."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Turn the commercial VPN OFF"
if [[ "$NODE_REACHABLE" -eq 0 ]]; then
  warn "No address was ever assigned, so there is nothing to measure against."
  MEASUREMENT_FAILED=1
  { echo "vpn_state=not-measured"; echo "geolocation=not-measured"
    echo "session_kind=aborted-before-measurement"; } > "$RUN_DIR/path-state.txt"
else
  warn "Everything measured from here must run on the bare China Telecom path."
  warn "A measurement taken through the commercial VPN is a different experiment"
  warn "and must never be recorded as direct-route evidence."
  printf '\n'
  step "Quit Shadowrocket / any other VPN client completely."
  step "Confirm the laptop is tethered to the China Telecom 5G handset in Hangzhou."
  step "Pause downloads, cloud backups and OS updates. Keep the handset still."
  printf '\n'
  pause "Press Enter when the VPN is fully off."

  while true; do
    printf '\n'
    say "Checking the live path…"
    FAKE_DNS=$(dig +short +time=3 +tries=1 example.com 2>/dev/null | grep -c '^198\.18\.' || true)
    ORG=$(curl -4 -sS --max-time 10 https://ipinfo.io/org 2>/dev/null || echo unknown)
    CITY=$(curl -4 -sS --max-time 10 https://ipinfo.io/city 2>/dev/null || echo unknown)
    CC=$(curl -4 -sS --max-time 10 https://ipinfo.io/country 2>/dev/null || echo unknown)
    if [[ -z "$CC" || "$CC" == unknown ]]; then   # ipinfo itself may be unreachable from CN
      CC=$(curl -4 -sS --max-time 10 https://api.country.is 2>/dev/null \
           | jqp 'print(json.load(sys.stdin).get("country","unknown"))' 2>/dev/null || echo unknown)
      [[ "$CC" == unknown ]] || note "ipinfo.io unreachable; fell back to api.country.is"
    fi
    say "resolver  : $( [[ "$FAKE_DNS" -gt 0 ]] && echo 'FAKE-IP 198.18/15 — a tunnel is still capturing DNS' || echo 'clean' )"
    say "public org: $ORG"
    say "location  : $CITY / $CC"
    printf '\n'

    if [[ "$FAKE_DNS" -gt 0 ]]; then
      warn "A VPN or proxy is still intercepting DNS. Turn it fully off."
    elif printf '%s' "$ORG$CC" | grep -Eqi 'gcore|g-core|akamai|linode|vultr|digitalocean|datacamp|m247|JP$'; then
      warn "The visible exit looks like a datacenter or a Japan exit, not China Telecom."
    elif [[ "$CC" == "CN" ]]; then
      say "Path looks like the bare China Telecom access network."
      { echo "vpn_state=off"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
        echo "geolocation=verified"
        echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
      break
    else
      warn "Country reads '$CC', expected CN."
      note "Both geolocation services being unreachable is itself plausible on bare"
      note "China Telecom and is not by itself evidence that a VPN is still up."
    fi

    # A clean resolver is the load-bearing check; geolocation is corroboration and
    # may simply be blocked. Allow the operator to vouch, but record that they did.
    printf '\n'
    if [[ "$FAKE_DNS" -eq 0 ]] \
       && confirm "Override: VPN is off and this is China Telecom 5G in Hangzhou. Proceed?"; then
      { echo "vpn_state=off-operator-confirmed"; echo "public_org=$ORG"; echo "city=$CITY"; echo "country=$CC"
        echo "geolocation=unverified"
        echo "local_time_cst=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S %Z %z')"; } > "$RUN_DIR/path-state.txt"
      warn "Recorded as operator-confirmed with unverified geolocation."
      break
    fi
    confirm "Re-check?" || { warn "Refusing to measure through a tunnel."; exit 1; }
  done
  ask SESSION_KIND "Session kind — off-peak or peak [off-peak]:"
  SESSION_KIND="${SESSION_KIND:-off-peak}"
  echo "session_kind=$SESSION_KIND" >> "$RUN_DIR/path-state.txt"
  pause "Press Enter to start measuring."
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Measure the raw route to the exit node"
set -a
# shellcheck source=/dev/null  # private run values written by this wizard
. "$ENV_FILE"
set +a
MEASURE_ALLOWED="$NODE_REACHABLE"
if ! proof_enforce_lifecycle_bounds "$RUN_DIR/state.json"; then
  warn "lifecycle boundary reached; skip measurement and destroy the proof node"
  MEASUREMENT_FAILED=1
  MEASURE_ALLOWED=0
fi
say "Target: the Droplet created in Stage 4. Output folder: $RUN_DIR"
say "This takes roughly 15 minutes. Leave the handset alone."
printf '\n'
warn "These iperf3 runs measure the RAW path to the Droplet, not traffic through"
warn "the Xray tunnel. They are not tunnel-throughput evidence and must not be"
warn "recorded as such. The route gate still needs a client-side measurement."
printf '\n'

if [[ "$MEASURE_ALLOWED" -eq 1 ]]; then
  run_measurement "control-start-ping-cloudflare" ping -c 100 1.1.1.1
  run_measurement "node-ping-100"                 ping -c 100 "$DROPLET_IP"
  run_measurement "node-traceroute-icmp"          traceroute -I -q 3 "$DROPLET_IP"
  run_measurement "node-traceroute-tcp443"        traceroute -P TCP -p 443 -q 3 "$DROPLET_IP"
  run_measurement "node-tcp443-connect"           python3 - "$DROPLET_IP" <<'PY'
import socket
import sys

host = sys.argv[1]
with socket.create_connection((host, 443), timeout=20):
    print("tcp/443 connected")
PY
  run_measurement "node-readiness-services"       ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    -i "$SSH_KEY" "root@$DROPLET_IP" 'set -e; systemctl is-active xray; command -v iperf3; /usr/local/bin/xray -version; /usr/local/bin/xray run -test -c /usr/local/etc/xray/config.json; ss -ltnp; ip -s link show; free -m; uptime'
  run_measurement "node-host-firewall-state"      ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    -i "$SSH_KEY" "root@$DROPLET_IP" 'set -e; if command -v ufw >/dev/null 2>&1; then ufw status verbose; fi; nft list ruleset 2>/dev/null || iptables-save'
  run_measurement "fetch-shadowrocket-profile"    scp -B -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
    -i "$SSH_KEY" "root@$DROPLET_IP:/root/vpn-gcore-proof/shadowrocket-vless-reality.uri" "$RUN_DIR/shadowrocket-vless-reality.uri"
  run_measurement "control-dns-state"             sh -c 'set -e; dig +short example.com; scutil --dns 2>/dev/null | sed -n "1,80p" || true'
  if ! api GET "/firewalls?per_page=200" > "$RUN_DIR/do-firewalls-readonly.json"; then
    warn "could not capture DigitalOcean firewall state"
    MEASUREMENT_FAILED=1
  fi

  if command -v iperf3 >/dev/null 2>&1; then
    # The server is off by default and only runs for these six transfers, so the
    # window in which an open iperf3 port could burn transfer allowance is
    # minutes rather than the whole lifecycle.
    run_measurement "node-iperf3-server-start" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
      -i "$SSH_KEY" "root@$DROPLET_IP" 'systemctl start iperf3; systemctl is-active iperf3'
    for i in 1 2 3; do
      run_measurement "node-resource-before-iperf3-down-$i" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
        -i "$SSH_KEY" "root@$DROPLET_IP" 'date -u; systemctl is-active xray iperf3; free -m; top -b -n1 | sed -n "1,20p"; ip -s link show'
      run_measurement "node-iperf3-down-$i" iperf3 -c "$DROPLET_IP" -R -t 30 -P 4
      run_measurement "node-resource-after-iperf3-down-$i" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
        -i "$SSH_KEY" "root@$DROPLET_IP" 'date -u; free -m; top -b -n1 | sed -n "1,20p"; ip -s link show'
      sleep 10
    done
    for i in 1 2 3; do
      run_measurement "node-resource-before-iperf3-up-$i" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
        -i "$SSH_KEY" "root@$DROPLET_IP" 'date -u; systemctl is-active xray iperf3; free -m; top -b -n1 | sed -n "1,20p"; ip -s link show'
      run_measurement "node-iperf3-up-$i" iperf3 -c "$DROPLET_IP" -t 30 -P 4
      run_measurement "node-resource-after-iperf3-up-$i" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
        -i "$SSH_KEY" "root@$DROPLET_IP" 'date -u; free -m; top -b -n1 | sed -n "1,20p"; ip -s link show'
      sleep 10
    done
    run_measurement "node-iperf3-server-stop" ssh -n -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
      -i "$SSH_KEY" "root@$DROPLET_IP" 'systemctl stop iperf3; systemctl is-active iperf3 || true'
  else
    note "iperf3 missing locally — install it for the upload direction (brew install iperf3)."
    MEASUREMENT_FAILED=1
  fi

  say "Now a 30-minute continuous latency run to expose bursts of loss."
  if confirm "Run it?"; then
    run_measurement "node-continuous-30min" ping -c 1800 "$DROPLET_IP"
  fi
  run_measurement "control-end-ping-cloudflare" ping -c 100 1.1.1.1
fi
if [[ "$MEASUREMENT_FAILED" -ne 0 ]]; then
  warn "One or more probes failed. This route session is invalid until explained."
fi
say "Raw output written to $RUN_DIR"
pause "Press Enter."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Record the result"
RESULT="$RUN_DIR/result.md"
{
  echo "# Candidate result: DigitalOcean $DO_SIZE in $DO_REGION"
  echo
  echo "> NOT Tokyo route evidence. DigitalOcean operates no Japan region."
  echo "> San Francisco candidates are tracked under docs/adr/0003."
  echo
  cat "$RUN_DIR/path-state.txt"
  echo
  echo "Raw captures: $RUN_DIR"
  if [[ "$MEASUREMENT_FAILED" -ne 0 ]]; then
    echo
    echo "Invalid-session reason: one or more measurement commands exited non-zero."
  fi
  echo
  sed -n '/^## Candidate$/,$p' "$REPO_ROOT/docs/benchmark-protocol.md" 2>/dev/null \
    || echo "Fill in from the result template in docs/benchmark-protocol.md."
} > "$RESULT"
INVALID_REASON=""
if [[ "$MEASUREMENT_FAILED" -ne 0 ]]; then
  INVALID_REASON="one or more measurement commands exited non-zero"
fi
proof_write_manifest "$RUN_DIR" "$INVALID_REASON"
say "Pre-filled result template: $RESULT"
say "Sanitized evidence manifest: $RUN_DIR/manifest.json"
note "The manifest is rewritten after Stage 8 so it records the destroyed state."
step "Fill in the measured values from the capture files."
step "Keep it in /private/tmp. Sanitize before anything reaches an issue."
warn "Never paste the Droplet address into GitHub."
pause "Press Enter when you are done reading."

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Destroy the Droplet and give the slot back"
say "The exit node is billed until destroyed. Powering it off does not help."
printf '\n'
say "Destroying Droplet id $DROPLET_ID via the guard, which refuses any target"
say "that is on the protected baseline or missing the '$TAG' tag."
printf '\n'
note "You will be asked to type the Droplet name: $DROPLET_NAME"
printf '\n'
proof_enforce_lifecycle_bounds "$RUN_DIR/state.json" \
  || warn "lifecycle boundary reached; destruction is the only allowed mutation."
api GET "/droplets?per_page=200" > "$RUN_DIR/pre-destroy-live-droplets.json"
proof_verify_destroy_boundary "$RUN_DIR/state.json" "$RUN_DIR/protected-ids.txt" "$RUN_DIR/pre-destroy-live-droplets.json" "$DROPLET_ID" \
  || { warn "destroy boundary is not exact — refusing mutation"; exit 1; }
authorize "destroy Droplet $DROPLET_ID" "Destroy Droplet $DROPLET_ID ($DROPLET_NAME) now?" || exit 1
if do_destroy_droplet "$DROPLET_ID"; then
  sleep 15
  api GET "/droplets?per_page=200" > "$RUN_DIR/post-destroy-live-droplets.json"
  if proof_verify_protected_baseline "$RUN_DIR/protected-ids.txt" "$RUN_DIR/post-destroy-live-droplets.json"; then
    say "Account is back to its protected baseline of $PROTECTED_COUNT Droplet(s)."
    PROOF_LIVE_DROPLET_ID=""   # nothing left to bill; stand the exit reminder down
    proof_record_destroyed "$RUN_DIR"
    proof_forget_env_keys "$ENV_FILE" DO_DROPLET_ID DO_DROPLET_IP DO_RUN_DIR
    # Rewrite the evidence manifest now that the lifecycle is closed. Written
    # only at Stage 7, it could never record anything but a still-live node.
    proof_write_manifest "$RUN_DIR" "$INVALID_REASON"
    say "Evidence manifest updated with the destroyed state: $RUN_DIR/manifest.json"
  else
    warn "Account does not exactly match the protected baseline. Check by hand."
  fi
  if [[ "$(_existing DO_SSH_KEY_UPLOADED || true)" == 1 ]]; then
    printf '\n'
    if authorize "delete experiment SSH key $KEY_ID" \
         "Delete the experiment SSH key from the DigitalOcean account?"; then
      if api DELETE "/account/keys/$KEY_ID" >/dev/null; then
        say "Deleted experiment SSH key id $KEY_ID."
        proof_forget_env_keys "$ENV_FILE" DO_SSH_KEY_ID DO_SSH_KEY_UPLOADED
      else
        warn "Could not delete experiment SSH key id $KEY_ID. Check by hand."
      fi
    else
      warn "Experiment SSH key was left in the account; delete key id $KEY_ID by hand."
    fi
  fi
  say "Also confirm no reserved IP or volume was left behind:"
  step "https://cloud.digitalocean.com/networking/reserved_ips"
  step "https://cloud.digitalocean.com/volumes"
else
  warn "NOT destroyed. The exit reminder below has the exact command."
fi
printf '\n'
note "To test another candidate, re-run this wizard and choose sfo3 or tor1."
note "Turn the commercial VPN back on when you are finished."

finish
if [[ "$MEASUREMENT_FAILED" -ne 0 ]]; then
  warn "Proof workflow finished cleanup, but the route session is invalid."
  exit 1
fi
